# Generated by Django 4.0.10 on 2026-08-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_printerprediction_normalized_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='powerplug_ip',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
